# Generated by Django 4.2.15 on 2024-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='description',
            field=models.TextField(default='tech creator', verbose_name='Creator description'),
        ),
        migrations.AddField(
            model_name='creator',
            name='nationality',
            field=models.CharField(default='world', max_length=40, verbose_name='Creator nacionality'),
        ),
        migrations.AddField(
            model_name='creator',
            name='picture',
            field=models.ImageField(blank=True, default='tech.png', upload_to='', verbose_name='Creator picture'),
        ),
    ]
