# Generated by Django 4.2.15 on 2024-08-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_creator_description_creator_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Creator description'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='nationality',
            field=models.CharField(max_length=40, verbose_name='Creator nacionality'),
        ),
    ]
