# Generated by Django 4.2.15 on 2026-06-14 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_alter_creator_description_alter_creator_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['name'], 'verbose_name': 'Creator', 'verbose_name_plural': 'Creators'},
        ),
    ]
