# Generated by Django 5.0.6 on 2024-07-10 01:23

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('creator', models.CharField(blank=True, max_length=40, verbose_name='Creator')),
                ('history', ckeditor.fields.RichTextField(blank=True, verbose_name='History')),
                ('description', ckeditor.fields.RichTextField(verbose_name='description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('documentation', models.URLField(max_length=50, verbose_name='Documentation')),
                ('slug', models.SlugField(max_length=20, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, default='tech.png', upload_to='', verbose_name='Logo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tech',
                'verbose_name_plural': 'Techs',
            },
        ),
    ]
