# Generated by Django 5.0.6 on 2024-07-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='image',
            field=models.ImageField(blank=True, default='tech.png', upload_to=''),
        ),
    ]
