# Generated by Django 4.2.15 on 2024-08-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='description',
            field=models.TextField(max_length=60, verbose_name='description'),
        ),
    ]
