# Generated by Django 5.0.6 on 2024-07-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='creator',
        ),
        migrations.AddField(
            model_name='tech',
            name='creator',
            field=models.ManyToManyField(to='creators.creator'),
        ),
    ]
