# Generated by Django 5.0.6 on 2024-07-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0002_remove_tech_creator_tech_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['name'], 'verbose_name': 'Tech', 'verbose_name_plural': 'Techs'},
        ),
        migrations.AlterField(
            model_name='tech',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, verbose_name='slug'),
        ),
    ]
