# Generated by Django 4.2.15 on 2024-08-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0002_alter_tech_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='description',
            field=models.TextField(max_length=150, verbose_name='description'),
        ),
    ]
