# Generated by Django 5.0.6 on 2024-07-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0003_alter_tech_options_alter_tech_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='visivility',
            field=models.BooleanField(default=False),
        ),
    ]
