# Generated by Django 5.0.6 on 2024-07-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0004_tech_visivility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech',
            old_name='visivility',
            new_name='visibility',
        ),
    ]
