# Generated by Django 5.0.6 on 2024-07-16 01:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_feature_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
